#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-authentik-outpost
SERVICE_NAME="outpost-radius"

check_container_initialized
check_service_initialized init 20-authentik-outpost

liftoff

print_start "Starting Authentik outpost (radius) $(grep -o "ADD: Authentik .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}')"
export HOME=/opt/authentik
outpost_map_proxy
outpost_map_logging
outpost_run_logged radius "${RADIUS_LOG_TYPE}" "${RADIUS_LOG_PATH}" "${RADIUS_LOG_FILE}" /usr/local/bin/authentik-radius
