#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-authentik
SERVICE_NAME="authentik-outpost-proxy"

check_container_initialized
check_service_initialized init 20-authentik

liftoff

if authentik_mode_enabled server ; then
    export AUTHENTIK_LISTEN__HTTP="[::]:9001"
    export AUTHENTIK_LISTEN__HTTPS="[::]:9444"
    export AUTHENTIK_LISTEN__METRICS="[::]:9302"
fi

print_start "Starting Authentik  $(grep -o "ADD: Authentik .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}') proxy outpost"
export VIRTUAL_ENV=/opt/authentik
export PATH="/opt/authentik/bin:/usr/local/bin:${PATH}"
export HOME=/opt/authentik
authentik_map_proxy
authentik_map_paths
authentik_map_logging "${PROXY_LOG_LEVEL}"
cd /usr/share/authentik
authentik_run_logged proxy "${PROXY_LOG_TYPE}" "${PROXY_LOG_PATH}" "${PROXY_LOG_FILE}" /usr/local/bin/authentik proxy
